cluster.name: elasticsearch
node.master: true
node.data: true
path.data: /usr/share/elasticsearch/data/
index.number_of_shards: 5
index.number_of_replicas: 0
network.host: 0.0.0.0
client.transport.sniff: false
script.inline: true
script.indexed: true
index.store.type: mmapfs
action.disable_delete_all_indices: true
bootstrap.mlockall: true
http.max_content_length: 10mb